### ISSUE TITLE
Systolic & diastolic blood pressure the wrong way round

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/opal-observations#1]
First!

**Comment by michaeledwardmarks** [comment]
Based on the above commit should this have been fixed now?

**Comment by davidmiller** [comment]
I think these are now Systolic then Diastolic everywhere, & they hook up. 

Deployed to elcid-opat.

**Comment by davidmiller** [comment]
@michaeledwardmarks - missed your comment - yes I believe fixed.

**Comment by GabPoll** [comment]
looks ok, but problems with table & graphs. Will raise separately

**Comment by GabPoll** [comment]
Sorry, on patient details view, it's still not correct. It's showing diastolic / systolic. Other way round please. It's correct on table, on graph and in modal.

**Comment by michaeledwardmarks** [comment]
Agree. Fine everywhere now except patient detail view.

**Comment by davidmiller** [comment]
Deployed to elcid-search !

**Comment by michaeledwardmarks** [comment]
Think this is finally correct!

**Comment by davidmiller** [comment]
Awesome sauces.  

I think this holds the record for "Number of times David thought the issue was fixed but really wasn't" !
